### ISSUE TITLE
requirement not available

### ISSUE THREAD

**Issue by DonatasFe** [akamai/akamai-gtm-metrics-exporter#1]
https://github.com/akamai/akamai-gtm-metrics-exporter/blob/e52db910e53193c80dc176583d2ad7a08369ec0e/go.sum#L4

`github.com/Knetic/govaluate@v3.0.1-0.20171022003610-9aa49832a739+incompatible: invalid pseudo-version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/dac3237ce23c7a321475df4e3bb8c7115ea5c093fdf9bc1798a57a9ef75ede77: exit status 128:`

**Comment by jdgri** [comment]
Package not part of build
