### ISSUE TITLE
Unable to get traffic report for datacenter 3131

### ISSUE THREAD

**Issue by wilsonLoblaw** [akamai/akamai-gtm-metrics-exporter#2]
Hi!

I am trying trying to setup the gtm metrics exporter but am getting the following error when i try to retrieve metrics.

`ERRO[0011] Unable to get traffic report for datacenter 3131 ... Skipping. Error: json: Unmarshal(non-pointer map[string]interface {})  source="datacenter_collector.go:123"
ERRO[0011] Unable to get traffic report for property wlb.app ... Skipping. Error: json: Unmarshal(non-pointer map[string]interface {})  source="property_collector.go:118"`

I am running the exporter locally using the following command( keys blanked out)
`./akamai-gtm-metrics-exporter \
--config.file="./test-config.yml" \
--web.listen-address=":9800" \
--gtm.edgegrid-host=*********************.luna.akamaiapis.net \
--gtm.edgegrid-client-secret=********************* \
--gtm.edgegrid-client-token=********************* \
--gtm.edgegrid-access-token=********************* \
--log.level="debug" \
--log.format="logger:stderr" \`

and my config file file is below with certain details blanked out
`domains:
  - domain_name: xxxxxxxxxxx.ca.akadns.net
    properties:
      - property_name: wlb.app
        datacenter:
          - 3131
        dc_nickname: 
          - xxxxxxxxxx
        target_name:
          - wlb.app

    datacenters:                          
      - datacenter_id: 3131
        property:
          - wlb.app

summary_window: 2d

prefill_window: 1h

timestamp_label: false

traffic_timestamp: false`

Any help would be much appreciated!

**Comment by edglynes** [comment]
The exporter is an add on to Prometheus. Prometheus does the collection, storage and graphing.

**Comment by jdgri** [comment]
Bug fix complete.
